Update plugin-proposal-optional-chaining-assign.md docs to work (#2882)
* Update plugin-proposal-optional-chaining-assign.md to work with required version field

When installing this plugin I received this error and needed to fix it as such

Error: [BABEL] /Users/blackmad/Code/gen2-blackmadeco/src/index.tsx: @babel/plugin-syntax-optional-chaining-assign: '.version' option required, representing the last proposal update. Currently, the only supported value is '2023-07'. (While processing: "/Users/blackmad/Code/gen2-blackmadeco/node_modules/@babel/plugin-proposal-optional-chaining-assign/lib/index.js$inherits")

* update version docs

* add it to the early stages sidebar

* Update docs/plugin-proposal-optional-chaining-assign.md

Co-authored-by: Nicolò Ribaudo <hello@nicr.dev>

* fix sidebar label

---------

Co-authored-by: Huáng Jùnliàng <jlhwung@gmail.com>
Co-authored-by: Nicolò Ribaudo <hello@nicr.dev>